# Generated by Django 2.0.4 on 2018-04-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('coordinates_lat', models.FloatField(verbose_name='lat')),
                ('coordinates_lan', models.FloatField(verbose_name='lan')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('river', models.CharField(max_length=30, verbose_name='Река')),
                ('power', models.IntegerField(verbose_name='Мощность')),
                ('annual_average', models.FloatField(verbose_name='Среднегодовая выработка')),
                ('area_reservoir', models.IntegerField(verbose_name='Площадь водохранилища')),
            ],
        ),
    ]
