# Generated by Django 2.0.4 on 2018-04-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ges',
            name='coordinates_lan',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='lan'),
        ),
        migrations.AlterField(
            model_name='ges',
            name='coordinates_lat',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='lat'),
        ),
    ]
