# Generated by Django 2.0.4 on 2018-04-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ges', '0002_auto_20180418_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ges',
            name='annual_average',
            field=models.FloatField(blank=True, verbose_name='Среднегодовая выработка'),
        ),
        migrations.AlterField(
            model_name='ges',
            name='area_reservoir',
            field=models.IntegerField(blank=True, verbose_name='Площадь водохранилища'),
        ),
    ]
